name: basic syntax of Github-action
on:
  workflow_dispatch: 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:      
      - name: checkout the repo
        uses: actions/checkout@v2
      - name: listing the files
        run: |
          chmod 777 *          
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
        # - name: Super-linter
        # we have taken this from github/marketplace https://github.com/marketplace/actions/super-linter
        # uses: super-linter/super-linter@v6.6.0
      - name: listing out the directories
        run: ls -ltr
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: deploying the code
        run: echo "Deploying to the target maching"
