name: Displaying the context info
on:
  push:
    branches: main
jobs:
  contexts:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'SaiPrabhu1239' }}
    steps:
      - name: Displaying GitHub Context
        run: echo '${{ toJSON(github) }}'
  JOB-Context:
    runs-on: ubuntu-latest
    if: ${{ job.status == 'failure' }}
    needs: contexts
    steps:
      - name: Displaying JOB context
        run: echo '${{ toJSON(job) }}'       
      - name: Displaying STEPS context
        run: echo '${{ toJSON(steps) }}'
  
