name: Displaying the context info
on:
  push:
    branches: main
jobs:
  contexts:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'Rajitha1239' }}
    steps:
      - name: Displaying GitHub Context
        run: echo '${{ toJSON(github) }}'
      - name: Displaying JOB context
        run: echo '${{ toJSON(job) }}'       
      - name: Displaying STEPS context
        run: echo '${{ toJSON(steps) }}'
  
