name: Accessing the declared secrets
on:
  push:
    branches: main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Accessing the secrets
        run: |
          echo "Accessing the declared secrets: ${{ secrets.VAR1 }}"
